name: Build and push Conduit frontend

on: 
  push:
    branches:
      - main
      - configure-ci/cd
      
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v4
        with: 
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GIT_TOKEN }}   
      
      - name: Build and push to GHCR
        id: build
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true 
          tags: ghcr.io/${{ github.repository_owner }}/${{ vars.FRONTEND_SERVICE_NAME }}:${{ github.sha }}
        
  call-deploy-workflow:
    needs: build
    uses: vbortnyk/conduit-deployment/.github/workflows/single-service-deployment.yml@ci/setup
    secrets: inherit
    with:
      SERVICE_NAME: ${{ vars.FRONTEND_SERVICE_NAME }}
      TAG: ${{ github.sha }}
      PORT: ${{ vars.FRONTEND_PORT }}
      VPS_HOST: ${{ vars.VPS_HOST }}
      VPS_USERNAME: ${{ vars.VPS_USERNAME }}
 